#!/usr/bin/env python
# Copyright ClusterHQ Inc.  See LICENSE file for details.
"""
Publish Installer images.
"""

from _preamble import TOPLEVEL, BASEPATH

import logging
import sys

# Log information about network connections
logging.basicConfig()
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

if __name__ == '__main__':
    from admin.installer import publish_installer_images_main as main
    main(sys.argv[1:], top_level=TOPLEVEL, base_path=BASEPATH)
